<?php
/**
 * Created by PhpStorm.
 * User: sajadweb
 * Date: 10/17/2016
 * Time: 11:57 AM
 */

namespace App\Packages\Tools\Firebase;


class UserPush extends Notification
{
    // TODO: Change the autogenerated stub
    static public function send($regId, $title, $message, $path = '',$android=0)
    {
        $return = parent::send($regId, $title, $message, $path,$android);
        return $return;
    }
}